"use client"

import { motion } from "framer-motion"
import { Clock } from "lucide-react"

interface TimelineEvent {
  year: string
  title: string
  description: string
}

export function HistoryTimeline() {
  const timelineEvents: TimelineEvent[] = [
    {
      year: "2019",
      title: "The Beginning",
      description:
        "PSQRD was founded by Dr. Elena Chen after her groundbreaking research on factual consistency in large language models at Stanford NLP.",
    },
    {
      year: "2020",
      title: "Seed Funding",
      description:
        "Raised $5M in seed funding to develop our core technology for eliminating AI hallucinations and ensuring factual accuracy.",
    },
    {
      year: "2021",
      title: "First Product Launch",
      description:
        "Launched our first product, PSQRD Verify, providing factual verification for content generated by large language models.",
    },
    {
      year: "2022",
      title: "Series A Funding",
      description:
        "Secured $25M in Series A funding to expand our team and develop enterprise solutions for media, legal, and financial sectors.",
    },
    {
      year: "2023",
      title: "Enterprise Expansion",
      description:
        "Expanded to serve enterprise clients across multiple industries, with a focus on regulated sectors requiring high accuracy.",
    },
    {
      year: "2024",
      title: "Global Growth",
      description:
        "Opened offices in New York and London, growing our team to over 100 employees worldwide and serving clients globally.",
    },
  ]

  return (
    <section className="py-16 px-4 md:px-8 bg-black/10">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center justify-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 text-purple-300 border border-purple-500/20 mb-4">
            <Clock className="w-4 h-4" />
            <span className="text-sm font-medium">Our Journey</span>
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">The PSQRD Story</h2>
          <p className="text-white/80 max-w-2xl mx-auto">
            From academic research to industry leader in trustworthy AI, our journey has been driven by a commitment to
            accuracy and transparency.
          </p>
        </motion.div>

        <div className="relative">
          {/* Timeline line */}
          <div className="absolute left-0 md:left-1/2 top-0 bottom-0 w-px bg-purple-500/20 transform md:translate-x-0 translate-x-[7px]"></div>

          <div className="space-y-12">
            {timelineEvents.map((event, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className={`relative flex flex-col md:flex-row gap-8 ${
                  index % 2 === 0 ? "md:flex-row" : "md:flex-row-reverse"
                }`}
              >
                <div className="md:w-1/2 flex md:justify-end">
                  <div
                    className={`bg-black/20 backdrop-blur-sm border border-purple-500/20 rounded-lg p-6 ${
                      index % 2 === 0 ? "md:text-right" : ""
                    }`}
                  >
                    <div className="text-purple-400 font-bold text-xl mb-2">{event.year}</div>
                    <h3 className="text-xl font-semibold mb-2">{event.title}</h3>
                    <p className="text-white/70">{event.description}</p>
                  </div>
                </div>

                {/* Timeline dot */}
                <div className="absolute left-0 md:left-1/2 w-3 h-3 bg-purple-500 rounded-full transform md:translate-x-[-6px] translate-x-[0px] mt-6"></div>

                <div className="md:w-1/2"></div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
